[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.build]
cmds = ["cd server && npm install --include=dev && npm run build"]

[start]
cmd = "cd server && NODE_OPTIONS='--max-old-space-size=512' npm run start"
